server.port = 8889

spring.application.name=Vocabulary
logging.level.net.medrag=info
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
voc.db-url=
user.user=
